title: "Sev FORNER — Portfolio"
description: "Gameplay / AI / Tools Programmer"
author: "StazixLS"
avatar: "https://github.com/StazixLS.png?size=64"

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - SETUP.md
  - preview.html
  - preview-project.html
